"""
Elderly-care symptom flows for the Care.AI care chatbot.

Not in MediCare AI: added for CareAI's older-adult population. Red flags follow
widely used public triage guidance (stroke signs, acute breathlessness, head
injury on anticoagulants, acute urinary retention, one-sided leg swelling).
These flows are NOT clinically validated. Schema: see care_bot_flows.py.
"""

ELDERLY_FLOWS = {
    "breathlessness": {
        "title": {"en": "Breathlessness", "nl": "Kortademigheid", "de": "Atemnot"},
        "topic": {"en": "your breathing", "nl": "uw ademhaling", "de": "Ihre Atmung"},
        "keywords": {
            "en": ["short of breath", "shortness of breath", "breathless", "out of breath", "difficulty breathing",
                   "trouble breathing", "hard to breathe", "wheezing", "wheeze"],
            "nl": ["kortademig", "benauwd", "ademnood", "buiten adem", "piepende ademhaling", "moeilijk ademen"],
            "de": ["atemnot", "kurzatmig", "luftnot", "außer atem", "pfeifende atmung", "schwer atmen"],
        },
        "questions": [
            {"id": "br_rest", "stop_on_yes": True,
             "text": {"en": "Are you breathless while sitting still, unable to finish a sentence, or are your lips turning blue or grey?",
                      "nl": "Bent u kortademig terwijl u stilzit, kunt u geen zin afmaken, of worden uw lippen blauw of grauw?",
                      "de": "Sind Sie in Ruhe kurzatmig, können Sie keinen Satz zu Ende sprechen, oder werden Ihre Lippen bläulich oder grau?"},
             "short": {"en": "Breathless at rest or blue lips", "nl": "Benauwd in rust of blauwe lippen", "de": "Atemnot in Ruhe oder blaue Lippen"}},
            {"id": "br_spo2", "stop_on_yes": True,
             "text": {"en": "If you have a pulse oximeter: is your oxygen reading below 92%?",
                      "nl": "Als u een saturatiemeter heeft: is uw zuurstofwaarde lager dan 92%?",
                      "de": "Falls Sie ein Pulsoximeter haben: Liegt Ihr Sauerstoffwert unter 92 %?"},
             "short": {"en": "Oxygen below 92%", "nl": "Zuurstof onder 92%", "de": "Sauerstoff unter 92 %"}},
            {"id": "br_sudden", "stop_on_yes": False,
             "text": {"en": "Did it come on suddenly, or much faster than usual?",
                      "nl": "Kwam het plotseling op, of veel sneller dan normaal?",
                      "de": "Kam es plötzlich oder viel schneller als sonst?"},
             "short": {"en": "Sudden onset", "nl": "Plotseling ontstaan", "de": "Plötzlich aufgetreten"}},
            {"id": "br_fever", "stop_on_yes": False,
             "text": {"en": "Do you also have a fever, or a cough with coloured phlegm?",
                      "nl": "Heeft u ook koorts, of hoest u gekleurd slijm op?",
                      "de": "Haben Sie zusätzlich Fieber oder Husten mit farbigem Auswurf?"},
             "short": {"en": "Fever or coloured phlegm", "nl": "Koorts of gekleurd slijm", "de": "Fieber oder farbiger Auswurf"}},
            {"id": "br_known", "stop_on_yes": False,
             "text": {"en": "Do you have COPD, asthma or heart failure, and is this worse than your usual?",
                      "nl": "Heeft u COPD, astma of hartfalen, en is dit erger dan normaal?",
                      "de": "Haben Sie COPD, Asthma oder Herzschwäche, und ist es schlimmer als sonst?"},
             "short": {"en": "Known lung/heart condition, worse than usual", "nl": "Bekende long-/hartziekte, erger dan normaal",
                       "de": "Bekannte Lungen-/Herzerkrankung, schlimmer als sonst"}},
        ],
        "rules": [
            {"any": ["br_rest", "br_spo2"], "level": "emergency"},
            {"any": ["br_sudden", "br_fever", "br_known"], "level": "urgent"},
        ],
        "default": "soon",
        "advice": {
            "en": ["Sit upright, leaning slightly forward, and breathe slowly.",
                   "If you have an action plan or reliever inhaler, follow it.",
                   "Avoid exertion until you have been assessed."],
            "nl": ["Ga rechtop zitten, iets voorovergebogen, en adem rustig.",
                   "Volg uw actieplan of gebruik uw luchtwegverwijder, als u die heeft.",
                   "Vermijd inspanning tot u bent beoordeeld."],
            "de": ["Setzen Sie sich aufrecht, leicht nach vorn gebeugt, und atmen Sie langsam.",
                   "Folgen Sie Ihrem Notfallplan oder nutzen Sie Ihr Bedarfsspray, falls vorhanden.",
                   "Vermeiden Sie Anstrengung, bis Sie untersucht wurden."],
        },
    },

    "fall_dizziness": {
        "title": {"en": "Fall or dizziness", "nl": "Val of duizeligheid", "de": "Sturz oder Schwindel"},
        "topic": {"en": "your fall or dizziness", "nl": "uw val of duizeligheid", "de": "Ihren Sturz oder Schwindel"},
        "keywords": {
            "en": ["fell", "fall", "fallen", "fell over", "tripped", "dizzy", "dizziness", "lightheaded", "light-headed",
                   "unsteady", "lost my balance", "vertigo"],
            "nl": ["gevallen", "val", "gestruikeld", "duizelig", "duizeligheid", "licht in het hoofd", "wankel",
                   "evenwicht kwijt"],
            "de": ["gestürzt", "sturz", "hingefallen", "gestolpert", "schwindel", "schwindlig", "benommen",
                   "gleichgewicht verloren", "unsicher auf den beinen"],
        },
        "questions": [
            {"id": "fall_head", "stop_on_yes": True,
             "text": {"en": "Did you hit your head or black out?",
                      "nl": "Heeft u uw hoofd gestoten of bent u buiten bewustzijn geweest?",
                      "de": "Haben Sie sich den Kopf gestoßen oder das Bewusstsein verloren?"},
             "short": {"en": "Head injury or blackout", "nl": "Hoofd gestoten of bewusteloos", "de": "Kopfverletzung oder Bewusstlosigkeit"}},
            {"id": "fall_hurt", "stop_on_yes": True,
             "text": {"en": "Are you unable to get up or put weight on a leg, or is there severe pain?",
                      "nl": "Kunt u niet opstaan of niet op een been steunen, of heeft u hevige pijn?",
                      "de": "Können Sie nicht aufstehen oder ein Bein nicht belasten, oder haben Sie starke Schmerzen?"},
             "short": {"en": "Can't get up / bear weight, or severe pain", "nl": "Kan niet opstaan/steunen, of hevige pijn",
                       "de": "Kann nicht aufstehen/belasten oder starke Schmerzen"}},
            {"id": "fall_neuro", "stop_on_yes": True,
             "text": {"en": "Do you have new weakness, numbness, slurred speech, a drooping face or double vision?",
                      "nl": "Heeft u nieuw krachtsverlies, een doof gevoel, onduidelijke spraak, een scheve mond of dubbelzien?",
                      "de": "Haben Sie neue Schwäche, Taubheit, verwaschene Sprache, ein hängendes Gesicht oder Doppelbilder?"},
             "short": {"en": "New stroke-like signs", "nl": "Nieuwe beroerte-achtige klachten", "de": "Neue schlaganfallähnliche Zeichen"}},
            {"id": "fall_thinners", "stop_on_yes": False,
             "text": {"en": "Do you take blood thinners?",
                      "nl": "Gebruikt u bloedverdunners?",
                      "de": "Nehmen Sie Blutverdünner?"},
             "short": {"en": "Takes blood thinners", "nl": "Gebruikt bloedverdunners", "de": "Nimmt Blutverdünner"}},
            {"id": "fall_repeat", "stop_on_yes": False,
             "text": {"en": "Have you fallen or felt dizzy more than once in the last few weeks?",
                      "nl": "Bent u de afgelopen weken vaker dan eens gevallen of duizelig geweest?",
                      "de": "Sind Sie in den letzten Wochen mehr als einmal gestürzt oder schwindlig gewesen?"},
             "short": {"en": "Repeated falls or dizziness", "nl": "Herhaaldelijk gevallen of duizelig", "de": "Wiederholte Stürze oder Schwindel"}},
        ],
        "rules": [
            {"any": ["fall_head", "fall_hurt", "fall_neuro"], "level": "emergency"},
            {"any": ["fall_thinners"], "level": "urgent"},
        ],
        "default": "soon",
        "advice": {
            "en": ["Get up slowly: roll onto your side, kneel, then use a sturdy chair.",
                   "Sit or lie down straight away if you feel dizzy.",
                   "Stand up slowly and drink enough fluids."],
            "nl": ["Sta langzaam op: rol op uw zij, kom op uw knieën en gebruik een stevige stoel.",
                   "Ga meteen zitten of liggen als u duizelig wordt.",
                   "Sta langzaam op en drink voldoende."],
            "de": ["Stehen Sie langsam auf: auf die Seite rollen, knien, dann an einem stabilen Stuhl hochziehen.",
                   "Setzen oder legen Sie sich sofort hin, wenn Ihnen schwindlig wird.",
                   "Stehen Sie langsam auf und trinken Sie ausreichend."],
        },
    },

    "confusion": {
        "title": {"en": "Sudden confusion", "nl": "Plotselinge verwardheid", "de": "Plötzliche Verwirrtheit"},
        "topic": {"en": "the confusion", "nl": "de verwardheid", "de": "die Verwirrtheit"},
        "keywords": {
            "en": ["confused", "confusion", "disoriented", "disorientated", "not making sense", "muddled", "delirium",
                   "acting strangely", "not himself", "not herself"],
            "nl": ["verward", "verwardheid", "in de war", "gedesoriënteerd", "delier", "vreemd gedrag"],
            "de": ["verwirrt", "verwirrtheit", "desorientiert", "durcheinander", "delir", "seltsames verhalten"],
        },
        "questions": [
            {"id": "conf_stroke", "stop_on_yes": True,
             "text": {"en": "Is there a drooping face, arm weakness or slurred speech?",
                      "nl": "Is er een scheve mond, krachtsverlies in een arm of onduidelijke spraak?",
                      "de": "Gibt es ein hängendes Gesicht, Armschwäche oder verwaschene Sprache?"},
             "short": {"en": "Face, arm or speech changes", "nl": "Mond, arm of spraak veranderd", "de": "Gesicht, Arm oder Sprache verändert"}},
            {"id": "conf_drowsy", "stop_on_yes": True,
             "text": {"en": "Is the person very drowsy, hard to wake, or having a fit?",
                      "nl": "Is de persoon erg suf, moeilijk wekbaar, of heeft die een aanval?",
                      "de": "Ist die Person sehr schläfrig, schwer weckbar oder hat sie einen Krampfanfall?"},
             "short": {"en": "Very drowsy, hard to wake, or a fit", "nl": "Erg suf, moeilijk wekbaar of een aanval",
                       "de": "Sehr schläfrig, schwer weckbar oder Krampfanfall"}},
            {"id": "conf_sudden", "stop_on_yes": False,
             "text": {"en": "Did the confusion start suddenly, over hours or a few days?",
                      "nl": "Is de verwardheid plotseling ontstaan, in uren of enkele dagen?",
                      "de": "Ist die Verwirrtheit plötzlich aufgetreten, innerhalb von Stunden oder wenigen Tagen?"},
             "short": {"en": "Started suddenly", "nl": "Plotseling ontstaan", "de": "Plötzlich aufgetreten"}},
            {"id": "conf_infection", "stop_on_yes": False,
             "text": {"en": "Is there a fever, a new cough, or burning when passing urine?",
                      "nl": "Is er koorts, een nieuwe hoest, of een branderig gevoel bij het plassen?",
                      "de": "Gibt es Fieber, neuen Husten oder Brennen beim Wasserlassen?"},
             "short": {"en": "Signs of infection", "nl": "Tekenen van infectie", "de": "Zeichen einer Infektion"}},
            {"id": "conf_meds", "stop_on_yes": False,
             "text": {"en": "Has any medication been started or changed recently?",
                      "nl": "Is er onlangs een medicijn gestart of veranderd?",
                      "de": "Wurde kürzlich ein Medikament neu begonnen oder geändert?"},
             "short": {"en": "Recent medication change", "nl": "Recente medicatiewijziging", "de": "Kürzliche Medikamentenänderung"}},
        ],
        "rules": [
            {"any": ["conf_stroke", "conf_drowsy"], "level": "emergency"},
            {"any": ["conf_sudden", "conf_infection"], "level": "urgent"},
        ],
        "default": "soon",
        "advice": {
            "en": ["Stay with the person and keep them calm and safe.",
                   "Make sure they drink, and can see and hear well (glasses, hearing aid).",
                   "Write down when the change started — the care team will ask."],
            "nl": ["Blijf bij de persoon en houd die rustig en veilig.",
                   "Zorg dat de persoon drinkt en goed kan zien en horen (bril, gehoorapparaat).",
                   "Schrijf op wanneer de verandering begon — het zorgteam zal ernaar vragen."],
            "de": ["Bleiben Sie bei der Person und sorgen Sie für Ruhe und Sicherheit.",
                   "Achten Sie darauf, dass die Person trinkt und gut sieht und hört (Brille, Hörgerät).",
                   "Notieren Sie, wann die Veränderung begann — das Pflegeteam wird danach fragen."],
        },
    },

    "urinary": {
        "title": {"en": "Urinary problems", "nl": "Plasklachten", "de": "Blasenbeschwerden"},
        "topic": {"en": "your urinary symptoms", "nl": "uw plasklachten", "de": "Ihre Blasenbeschwerden"},
        "keywords": {
            "en": ["urine", "urinating", "passing urine", "peeing", "pee", "bladder", "urinary", "uti",
                   "water infection", "burning when i pee", "incontinence"],
            "nl": ["plassen", "urine", "blaasontsteking", "branderig plassen", "blaas", "incontinentie"],
            "de": ["urin", "wasserlassen", "blasenentzündung", "brennen beim wasserlassen", "blase",
                   "harnwegsinfekt", "inkontinenz"],
        },
        "questions": [
            {"id": "uri_retention", "stop_on_yes": True,
             "text": {"en": "Are you unable to pass urine at all, with a painful, swollen lower belly?",
                      "nl": "Kunt u helemaal niet plassen, met een pijnlijke, opgezette onderbuik?",
                      "de": "Können Sie gar kein Wasser lassen, mit schmerzhaftem, geblähtem Unterbauch?"},
             "short": {"en": "Cannot pass urine, painful belly", "nl": "Kan niet plassen, pijnlijke buik",
                       "de": "Kann kein Wasser lassen, schmerzhafter Bauch"}},
            {"id": "uri_fever", "stop_on_yes": False,
             "text": {"en": "Do you have a fever, shivering, or pain in your side or back?",
                      "nl": "Heeft u koorts, koude rillingen, of pijn in uw zij of rug?",
                      "de": "Haben Sie Fieber, Schüttelfrost oder Schmerzen in der Flanke oder im Rücken?"},
             "short": {"en": "Fever, shivering or side/back pain", "nl": "Koorts, rillingen of pijn in zij/rug",
                       "de": "Fieber, Schüttelfrost oder Flanken-/Rückenschmerz"}},
            {"id": "uri_blood", "stop_on_yes": False,
             "text": {"en": "Is there blood in your urine?",
                      "nl": "Zit er bloed in uw urine?",
                      "de": "Ist Blut in Ihrem Urin?"},
             "short": {"en": "Blood in urine", "nl": "Bloed in urine", "de": "Blut im Urin"}},
            {"id": "uri_burning", "stop_on_yes": False,
             "text": {"en": "Does it burn or sting, or do you need to go much more often?",
                      "nl": "Brandt of steekt het, of moet u veel vaker plassen?",
                      "de": "Brennt oder sticht es, oder müssen Sie viel häufiger?"},
             "short": {"en": "Burning or going more often", "nl": "Branderig of vaker plassen", "de": "Brennen oder häufiger"}},
        ],
        "rules": [
            {"any": ["uri_retention"], "level": "emergency"},
            {"any": ["uri_fever"], "level": "urgent"},
            {"any": ["uri_blood", "uri_burning"], "level": "soon"},
        ],
        "default": "self_care",
        "advice": {
            "en": ["Drink regularly through the day, unless you have been told to limit fluids.",
                   "Bring a urine sample to your GP practice if asked.",
                   "Watch for new confusion — in older adults an infection can show up that way."],
            "nl": ["Drink verspreid over de dag voldoende, tenzij u een vochtbeperking heeft.",
                   "Neem een urinemonster mee naar de huisartsenpraktijk als daarom wordt gevraagd.",
                   "Let op nieuwe verwardheid — bij ouderen kan een infectie zich zo uiten."],
            "de": ["Trinken Sie über den Tag verteilt ausreichend, sofern keine Trinkmengenbegrenzung besteht.",
                   "Bringen Sie auf Nachfrage eine Urinprobe in die Hausarztpraxis.",
                   "Achten Sie auf neue Verwirrtheit — bei älteren Menschen kann sich eine Infektion so zeigen."],
        },
    },

    "leg_swelling": {
        "title": {"en": "Swollen legs", "nl": "Dikke benen", "de": "Geschwollene Beine"},
        "topic": {"en": "your swollen legs", "nl": "uw dikke benen", "de": "Ihre geschwollenen Beine"},
        "keywords": {
            "en": ["swollen legs", "swollen leg", "leg swelling", "swollen ankles", "swollen ankle", "ankle swelling",
                   "swollen feet", "puffy ankles", "oedema", "edema", "swollen calf"],
            "nl": ["dikke benen", "dik been", "gezwollen benen", "gezwollen been", "dikke enkels", "gezwollen enkels",
                   "oedeem", "vocht in de benen"],
            "de": ["geschwollene beine", "geschwollenes bein", "dicke beine", "geschwollene knöchel", "ödem", "ödeme",
                   "wassereinlagerung", "wasser in den beinen", "geschwollene wade"],
        },
        "questions": [
            {"id": "leg_breath", "stop_on_yes": True,
             "text": {"en": "Are you also newly short of breath, or do you have chest pain?",
                      "nl": "Bent u daarnaast plotseling kortademig, of heeft u pijn op de borst?",
                      "de": "Sind Sie zusätzlich neu kurzatmig oder haben Sie Brustschmerzen?"},
             "short": {"en": "New breathlessness or chest pain", "nl": "Nieuwe benauwdheid of borstpijn", "de": "Neue Atemnot oder Brustschmerzen"}},
            {"id": "leg_one", "stop_on_yes": False,
             "text": {"en": "Is only one leg swollen, painful, warm or red?",
                      "nl": "Is maar één been dik, pijnlijk, warm of rood?",
                      "de": "Ist nur ein Bein geschwollen, schmerzhaft, warm oder gerötet?"},
             "short": {"en": "One leg only, painful/warm/red", "nl": "Eén been, pijnlijk/warm/rood", "de": "Nur ein Bein, schmerzhaft/warm/rot"}},
            {"id": "leg_weight", "stop_on_yes": False,
             "text": {"en": "Have you gained more than 2 kg in 3 days, or are you breathless lying flat?",
                      "nl": "Bent u in 3 dagen meer dan 2 kg aangekomen, of bent u benauwd als u plat ligt?",
                      "de": "Haben Sie in 3 Tagen mehr als 2 kg zugenommen oder bekommen Sie im Liegen schlecht Luft?"},
             "short": {"en": "Over 2 kg in 3 days or breathless lying flat", "nl": "Meer dan 2 kg in 3 dagen of benauwd plat liggend",
                       "de": "Über 2 kg in 3 Tagen oder Atemnot im Liegen"}},
            {"id": "leg_new", "stop_on_yes": False,
             "text": {"en": "Is the swelling new, or clearly worse than usual?",
                      "nl": "Is de zwelling nieuw, of duidelijk erger dan normaal?",
                      "de": "Ist die Schwellung neu oder deutlich stärker als sonst?"},
             "short": {"en": "New or worse than usual", "nl": "Nieuw of erger dan normaal", "de": "Neu oder stärker als sonst"}},
        ],
        "rules": [
            {"any": ["leg_breath"], "level": "emergency"},
            {"any": ["leg_one", "leg_weight"], "level": "urgent"},
            {"any": ["leg_new"], "level": "soon"},
        ],
        "default": "self_care",
        "advice": {
            "en": ["Raise your legs when sitting.", "Weigh yourself each morning if you have heart failure.",
                   "Keep taking your medicines as prescribed."],
            "nl": ["Leg uw benen omhoog als u zit.", "Weeg uzelf elke ochtend als u hartfalen heeft.",
                   "Blijf uw medicijnen innemen zoals voorgeschreven."],
            "de": ["Lagern Sie die Beine im Sitzen hoch.", "Wiegen Sie sich jeden Morgen, wenn Sie eine Herzschwäche haben.",
                   "Nehmen Sie Ihre Medikamente weiter wie verordnet ein."],
        },
    },
}
